# Generated by Django 4.2.16 on 2026-01-10 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0002_leaderboard_challenge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendship',
            options={'verbose_name': 'Дружба', 'verbose_name_plural': 'Друзья'},
        ),
        migrations.AlterModelOptions(
            name='userachievement',
            options={'verbose_name': 'Достижение пользователя', 'verbose_name_plural': 'Достижения пользователей'},
        ),
        migrations.RemoveField(
            model_name='leaderboard',
            name='rank',
        ),
        migrations.AddField(
            model_name='challenge',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Завершён'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='response_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ответ (очки)'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='time_played',
            field=models.DurationField(blank=True, null=True, verbose_name='Время игры'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='achievements/', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='difficulty',
            field=models.IntegerField(choices=[(3, '3x3'), (4, '4x4'), (5, '5x5')], verbose_name='Сложность'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='Принят'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='message',
            field=models.TextField(blank=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='target_score',
            field=models.IntegerField(verbose_name='Цель (очки)'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_out', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_in', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='difficulty',
            field=models.IntegerField(choices=[(3, '3x3'), (4, '4x4'), (5, '5x5')], verbose_name='Сложность'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='game_state',
            field=models.JSONField(verbose_name='Состояние игры'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Завершена'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Очки'),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='best_score',
            field=models.IntegerField(default=0, verbose_name='Лучшие очки'),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='date_achieved',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата достижения'),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
